apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-kafka
  template:
    metadata:
      labels:
        app: broker-kafka
    spec:
      containers:
        - name: broker-kafka
          image: confluentinc/cp-kafka:7.3.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:29092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker-kafka:29092
            # - name: KAFKA_ADVERTISED_LISTENERS
            #   value: LISTENER_BOB://broker_kafka:29092,LISTENER_FRED://localhost:9092
            # - name: KAFKA_INTER_BROKER_LISTENER_NAME
            #   value: LISTENER_BOB
            # - name: KAFKA_LISTENERS
            #   value: LISTENER_BOB://broker_kafka:29092,LISTENER_FRED://localhost:9092
            # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            #   value: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
            # - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            #   value: "1"
            # - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            #   value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:22181
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_NUM_PARTITIONS
              value: "1"
      restartPolicy: Always
