apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    service: {{ .Chart.Name }}
