CREATE DATABASE tickets;
GRANT ALL PRIVILEGES ON DATABASE tickets TO postgres;

CREATE DATABASE flights;
GRANT ALL PRIVILEGES ON DATABASE flights TO postgres;

CREATE DATABASE privileges;
GRANT ALL PRIVILEGES ON DATABASE privileges TO postgres;
